In [4]:
import numpy as np

a1 = np.array([10,20,5,3,19,9])

print(a1>10)

a = np.array([10,20,5,3,19,9], dtype=float)

res = (a - a.min()) / (a.max() - a.min())
print(res.tolist())

a2 = np.array([[1, 2], [3, 6], [8, 10]])
print(a2.flatten())

a3 = np.array([[1,2],[3,4]])
a4 = np.array([[5,6],[7,8]])

print(np.concatenate((a3, a4), axis=0))
print(np.concatenate((a3,a4), axis=1))

a5 = np.array([1,2,1])

print(np.unique(a5))

[False  True False False  True False]
[0.4117647058823529, 1.0, 0.11764705882352941, 0.0, 0.9411764705882353, 0.35294117647058826]
[ 1  2  3  6  8 10]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[1 2]
