In [59]:
import numpy as np

students = np.array([
    [101,78,85,90],
    [102,65,70,75],
    [103,80,88,82],
    [104,72,60,65],
    [105,90,95,92]
])
#average of all subjects
stud = students[0:, 1:]

print(stud)

print(np.average(stud, axis=0))

#subject with highest average

subjMax = np.average(stud, axis=0)
print(max(subjMax))

#print rollnumber where marks max sub1
stud1 = students[0:,1]
print(max(stud1))
roll = np.where(stud1 == max(stud1))
value = students[roll][0][0]
print(value)

[[78 85 90]
 [65 70 75]
 [80 88 82]
 [72 60 65]
 [90 95 92]]
[77.  79.6 80.8]
80.8
90
105
